gcc drystone_long.c -o O1-O2_diff/test1.out -O2 -fno-align-functions
gcc drystone_long.c -o O1-O2_diff/test2.out -O2 -fno-align-jumps
gcc drystone_long.c -o O1-O2_diff/test3.out -O2 -fno-align-labels
gcc drystone_long.c -o O1-O2_diff/test4.out -O2 -fno-align-loops
gcc drystone_long.c -o O1-O2_diff/test5.out -O2 -fno-caller-saves
gcc drystone_long.c -o O1-O2_diff/test6.out -O2 -fno-crossjumping
gcc drystone_long.c -o O1-O2_diff/test7.out -O2 -fno-cse-follow-jumps
gcc drystone_long.c -o O1-O2_diff/test8.out -O2 -fno-devirtualize
gcc drystone_long.c -o O1-O2_diff/test9.out -O2 -fno-expensive-optimizations
gcc drystone_long.c -o O1-O2_diff/test10.out -O2 -fno-gcse
gcc drystone_long.c -o O1-O2_diff/test11.out -O2 -fno-hoist-adjacent-loads
gcc drystone_long.c -o O1-O2_diff/test12.out -O2 -fno-inline-small-functions
gcc drystone_long.c -o O1-O2_diff/test13.out -O2 -fno-ipa-cp
gcc drystone_long.c -o O1-O2_diff/test14.out -O2 -fno-ipa-sra
gcc drystone_long.c -o O1-O2_diff/test15.out -O2 -fno-optimize-register-move
gcc drystone_long.c -o O1-O2_diff/test16.out -O2 -fno-optimize-sibling-calls
gcc drystone_long.c -o O1-O2_diff/test17.out -O2 -fno-optimize-strlen
gcc drystone_long.c -o O1-O2_diff/test18.out -O2 -fno-peephole2
gcc drystone_long.c -o O1-O2_diff/test19.out -O2 -fno-regmove
gcc drystone_long.c -o O1-O2_diff/test20.out -O2 -fno-reorder-blocks
gcc drystone_long.c -o O1-O2_diff/test21.out -O2 -fno-reorder-functions
gcc drystone_long.c -o O1-O2_diff/test22.out -O2 -fno-rerun-cse-after-loop
gcc drystone_long.c -o O1-O2_diff/test23.out -O2 -fno-schedule-insns2
gcc drystone_long.c -o O1-O2_diff/test24.out -O2 -fno-strict-aliasing
gcc drystone_long.c -o O1-O2_diff/test25.out -O2 -fno-thread-jumps
gcc drystone_long.c -o O1-O2_diff/test26.out -O2 -fno-tree-builtin-call-dce
gcc drystone_long.c -o O1-O2_diff/test27.out -O2 -fno-tree-pre
gcc drystone_long.c -o O1-O2_diff/test28.out -O2 -fno-tree-switch-conversion
gcc drystone_long.c -o O1-O2_diff/test29.out -O2 -fno-tree-tail-merge
gcc drystone_long.c -o O1-O2_diff/test30.out -O2 -fno-tree-vrp
